model:
    model_name: AE_DIT_DDC
    lr: 1.0e-5
    AE_DIT_DDC:
        encoder:
            downsample_factor: 4
        decoder:
            in_channels: 145
            out_channels: 145
            dim: 512
            num_heads: 8
            num_blocks: 8
            patch_size: 4
            nlat: 180
            nlon: 360
        scheduler:
            num_refinement_steps: 5
            num_train_steps: 11
            sigma_coupling: 1.0

data:
    train_data_path: /glade/derecho/scratch/ayz/AMIP_train_new.h5
    val_data_path: /glade/derecho/scratch/ayz/AMIP_valid_new.h5
    norm_stats_path: /glade/derecho/scratch/ayz/norm_stats_dict_new.pkl
    training_nsteps: 1
    val_nsteps: 1
    val_horizon: 1460
    use_climatology: False
    downsample_levels: 1
    batch_size: 1
    num_workers: 4
    clouds: False

training:
    seed: 42
    devices: 4
    accelerator: gpu
    strategy: ddp
    precision: 32-true 
    check_val_every_n_epoch: 1
    log_every_n_steps: 10
    max_epochs: 50
    ema_decay: 0.99
    num_sanity_val_steps: 1
    log_dir: /glade/derecho/scratch/ayz/AMIP_logs/
    project: amip
    wandb_mode: online
    checkpoint: null
    description: SI_DDC_DiT
    accumulate_grad_batches: 4
