model:
    model_name: flow
    lr: 5.0e-4
    flow:
        num_refinement_steps: 5
        num_train_steps: 21
        integrator: euler
    dit:
        

data:
    train_data_path: /glade/derecho/scratch/ayz/AMIP_train.h5
    val_data_path: /glade/derecho/scratch/ayz/AMIP_valid.h5
    climatology_path: /glade/derecho/scratch/ayz/climatology_1990_1996.pkl
    norm_stats_path: /glade/derecho/scratch/ayz/norm_stats_dict.pkl
        
    training_nsteps: 2
    val_nsteps: 41
    climatology_horizon: 7308 # 5year
    climatology_start: 32120

    batch_size: 16
    num_workers: 4

training:
    seed: 42
    devices: 1
    accelerator: gpu
    strategy: auto
    check_val_every_n_epoch: 1
    log_every_n_steps: 100
    max_epochs: 50
    log_dir: /glade/derecho/scratch/ayz/AMIP_logs/
    project: amip
    wandb_mode: online
    checkpoint: null